-- phpMyAdmin SQL Dump
-- version 4.0.10.14
-- http://www.phpmyadmin.net
--
-- Host: localhost:3306
-- Generation Time: Sep 19, 2016 at 07:27 AM
-- Server version: 5.5.49-cll-lve
-- PHP Version: 5.6.20

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `ps2016`
--

-- --------------------------------------------------------

--
-- Table structure for table `events`
--

CREATE TABLE IF NOT EXISTS `events` (
  `ID` int(11) DEFAULT NULL,
  `EventName` varchar(255) NOT NULL,
  `RegFee` varchar(255) NOT NULL,
  `First` varchar(255) NOT NULL,
  `Second` varchar(255) NOT NULL,
  `Coordinator` varchar(255) NOT NULL,
  `Contact` varchar(255) NOT NULL,
  `Description` text NOT NULL,
  `Venue` varchar(255) NOT NULL,
  `Date` varchar(255) NOT NULL,
  `Type` varchar(255) NOT NULL,
  PRIMARY KEY (`EventName`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `events`
--

INSERT INTO `events` (`ID`, `EventName`, `RegFee`, `First`, `Second`, `Coordinator`, `Contact`, `Description`, `Venue`, `Date`, `Type`) VALUES
(NULL, '', '', '', '', '', '', '', '', '', ''),
(35, 'ABB Makeathon', '200 per team of 4(Teams of 4 is compulsory)', '5000', '3000', 'Anirudh', '9448496283', '1. Submission of proposals with a modular approach to the solution - 18th Sept 2016<br>\r2. Announcement of short-listed proposals(5Nos.) - 21st Sept 2016<br>\r3. Presentation with  hardware of the  working module developed over two days  23rd and 24th Sept.Announcement of incentives to the winners  - 24th Sept 2016,2.30pm <br>\rProblem Statement  :<br>\rDesign of next generation automation system using low cost matured technologies<br>\rIn recent times, the low cost sensors have become inevitable in using them for various applications, Example: gyro, gps, accelerometers, magnetic compass in smartphones. Can a similar concept can be extended to automation system making use of low cost sensors, smart- phones, edge devices, cloud computing, smart historian. What can be done that would result productivity enhancement through integrating all of these low cost matured technologies, such as internet, low cost handheld computing devices, wireless connectivity, social media, ..etc.<br>\rTemplate for the proposal:<br>\rTitle: <br>\rAbstract: In 200 words<br>\rObjectives:<br>\rOutcomes:<br>\r The  overall block diagram :<br>\rBrief description of the Methodology:<br>\rExpected Results:<br>\rConclusion:<br>\rFuture Scope :<br>', 'Measurements lab EEE', '23 september', 'Event'),
(48, 'Abstrakt It!', 'Free for IEEE SSIT Members<br>Others : 100/person', '1000', '750', 'Vidhya T', '9663740919', 'IoT related IEEE paper will be provided with title and abstract covered printed on page.<br/>\nParticipants have to read the paper and write the abstract and title in the best possible way (30 minutes). Next round will be peer grading in which students have to review abstract written by other students.\n\nSponsored by IEEE SSIT ES Joint Chapter', 'PG block EC 6001', '23 september', 'Event'),
(65, 'Ad making', '100/team of 2', '2000', '1000', 'Ranjith', '9902264822', 'Participants will be shooting a video ad about the theme IoT.\r\rLast date for registration is 19 th September 2016. NO SPOT REGISTRATIONS.\rAll the registered participants will be updated on 19 th September 2016.', ' PG block  2nd floor MBA classroom 2', '23 september', 'Event'),
(51, 'Ad-Apt', '100/Team of 3-4', '1500', '1000', 'Hansa N', '8951621517', 'Teams of 3-4 are allowed. In first round the teams have to market certain products to a target audience within the campus. According to the marketing skills, the audience will give the teams fake currency. The top 4 teams with the most ?money? will progress to the second round. In the second round, the teams will be given a failed product which they have to make ?smart? using IoT and sell. (Basic IoT briefing will be given).', 'CIM Lab IEM Department', '23 september', 'Event'),
(9, 'ALLELES-a Biohunt', '100', '1500', '750', 'Priyanka', '9035895423', 'Rounds include a clue to crack in each. It includes clues regarding various fields of biotechnology and life sciences. Skipping of rounds shall add a penalty to the team. Participants are required to get a smartphone.', 'PG Biotech Dept', '23 september', 'Event'),
(26, 'Android App Development Embedded with IoT', '250', 'Nil', 'Nil', 'Ranjini R', '8123244404', 'Content of the workshop:<br>\rCypress BLE Solution Overview<br>\rBLE Architecture Overview<br>\rCypress BLE Modules<br>\rSet Up and Install PSoC Creator<br>\rCySmart Tool<br>\r Android Architecture<br>\r Developing Android Application to communicate with BLE<br>\rStoring the data to google form through Android App<br>\rParticipants will have to get Laptops, Android Phones.<br>', 'CS Lab', '24 September', ''),
(71, 'Assemble Me', '200/team of 2', '1500', '1000', ' Suraj Simha', '9916052713', 'Contestants must know SOLID Edge software. Parts to be designed and assembled will be having the theme of IOT. The parts will contain sensors and actuators shown as different shapes which form an integral part of IOT. \rParticipants will be given the task of modeling these shapes and assembling them to obtain a system that can perform specific function. Teams of 2.', 'CAD Lab Mechanical Block', '23 september', 'Event'),
(7, 'Astrophotography workshop', '50', 'Nil', 'Nil', 'Akshatha', '9945489210', '2-3 hour session on the basics of Astrophotography by Mr. Johann Nishat. Learn to capture star trails, deep sky objects and explore the possibilities of applying IOT in astrophotography! Get your Cameras (preferred, not compulsory).', 'PG 6003', '24 September', 'Workshop'),
(72, 'Best Mechanic', '300/team of 4', '1500', '1000', 'Shubham', '8088439668', 'The event consists of a single round where a team of 4 members are supposed to assemble the parts of an object given. The thing which has to be assembled will be said at the time of the event. Example: a car, an automotive part etc. They are supposed to assemble within the given time. The team which finishes first wins. All the components are provided by us. If they ruin any of the part, it will not be provided again. At the end of the event, the object they assemble should work properly. The model they make when connected to a controller, should work when controlled from any location using the process of IoT.', 'SOM Lab, Mechanical Department', '23 september', 'Event'),
(10, 'Bio-entertainment quotient', '100/Team', '2000', '1000', 'Devyani J', '9535110569', 'Quiz combining pop culture and high school biology. <br> Round 1-preliminary round <br> Round 2-final round, max of 10 teams will qualify.', 'M V Hall', '24 September', 'Event'),
(82, 'Biz-Tech Quiz', '100/team of 3', '6000', '3000', 'Rahul S', '7829076699', 'A quiz having everything from the world of business and technology. The quiz tracks business and technology trends through history till the cutting edge technologies like IoT,cyber systems etc. helping participants gain the perspective of businesses across the world.', 'Indoor Stadium', '24 September', 'Event'),
(66, 'Block and tackle', '50/person', '2000', '1000', 'Prannay', '9886099624', 'Block and tackle puts participants in situations where they have to contradict their\rown opinion on many issues including IOT.', 'PG block  3rd floor MBA Finance class', '24 September', 'Event'),
(37, 'Bomb Diffusion 3.0(Circuit challenge-TCE)', '100/- per team of 2. (Teams of 2 is compulsory)', '1500', '1000', 'Uma R', '8884322997', 'The preliminary round will have a written test on analog and digital electronics circuits. The teams qualifying for the next round/s shall be given incomplete/incorrect circuits which have to be debugged or completed to get the expected output in the shortest time. In collaboration with Circuit Challenge.', 'PG block EE-6002 and PE Lab', '23 september', 'Event'),
(74, 'Botwars', '400/team of max 4', '4000', 'Nil', 'Ayush Kohli', '9620628571', 'Multiple robots battling among themselves for the survival within the arena. Various rounds will be conducted based on the number of participants. Participants will be asked to submit their robot specs with pictures two day prior to the event which will be further updated on the Facebook page for strategic discussions. Participants have to get required robots and materials. Robot which is unable to move even after 30 sec after damage loses. The dimensions of the robot are 2ftx1ftx1ft.', 'MPH', '24 September', 'Event'),
(92, 'Buoyant', '300/team of 2', '2000', '1000', 'Ashwin', '9743067056', 'Single Round To Keep Thermocol And Cardboard Floating And Be Able To Move Through a given path using own methods.The model should hold good for buoyancy principle. Should only use thermocol and dc motor. Should move in the given track. Good design .', 'IT Classroom 3', '23 september', 'Event'),
(64, 'Business Plan Competition', '100/team of 2', '2000', '1000', 'Pawan A', '9738644173', 'Participants would be proposing a business plan based on the theme IoT. The\routcomes include Idea Generation to Launch - Feasibility of the plan.\r\rLast date for registration is 19 th September 2016. NO SPOT REGISTRATIONS.\rAll the registered participants will be updated on 19 th September 2016.', 'PG block  3rd floor MBA Finance class', '23 september', 'Event'),
(20, 'CheMUN', '100', '1000', '800', 'Avishek', '9008796499', 'Formal debate protocols will be followed. No cross talking, address only to the chair. If you want to speak, raise the placard of your name and we will recognize you. Duration of the event will be 3 hours with a break in between The final decision will be by the judges discretion and cannot be challenged. The judging will based on the quality of the content, confidence of the speaker and body language while addressing', 'PG Block 3002', '24 September', 'Event'),
(15, 'CHrash', '100/Team', '1800', '1000', 'Nikitha S P', '9916470865', 'Teams of 2 or 3. <br> Prelims: pen and paper test. Participants have to brainstorm and come up with solution to the set of engineering disaster related videos shown. <br> Final round: participants will be given to solve real time case on disasters and present their solution. <br> For both the rounds the final decision rests in the hands of judges.', '3001 PG Block', '23 september', 'Event'),
(79, 'CIMEATHON (BMSCE Exclusive)', '100/person', 'Upto 25000', 'Nil', 'Divya', '9986618110', 'The Hackathon will convene the interdisciplinary students from different disciplines over a period of 8 hours on Medical IOT in order to develop innovative ideas/prototype solutions (hardware/software) to address healthcare challenges of in India.<br/>\r Rules of the Hackathon:<br/>\rThe participants should work on one of the themes mentioned above during the above said hackathon.<br/>\rTeam Formation: Teams should have members with a mix of different technical background. You are welcome to form teams beforehand. But we do encourage to form the team at the start of the event so that you could really have a force of Multidisciplinary learning.<br/>\rResources: Participants in the hackathon can carry any materials with them related to the hackathon. For the Hackathon, participants are requested to carry their laptops. Wi-fi would be provided for all participants.<br/>\rMentorship: The team would get access to plethora of mentors who have expertise of clinical, technical, business, designing, etc.<br/>\rPartners: Ellipsonic, Philips, InnAccel, Villgro Foundation <br/>', 'Department of Medical Electronics, 5th floor, PG Block', '23 september', 'Event'),
(69, 'Code Storm', '150/team of 2', '2000', '1000', 'Harish Raghav V', '9611261166', 'IoT is the network of interconnected devices or things with sensors embedded, software, network connection and necessary electronics that enables them to collect and exchange data enabling responsiveness.Code storm event is about implementing use cases of IoT using ?Raspberry Pi? board, sensors and personal computers.<br/>\rRules:<br/>\rTeam of 2.<br/>\r Three rounds: Every round will be an elimination round. In Each round a single problem is defined to all the teams. The teams should come up with solutions. Based on the timing and the efficiency of the solution, the team advances to the next round. Two of the teams based on their performance in the final round will be awarded.<br/>\r Any of the programming language can be used.', ' MCA Lab', '23 september', 'Event'),
(80, 'Confoundo 2.0', '100/team of 2', '1500', '1000', 'Vivek', '7022150431', 'Confound your senses by taking our maths quiz. Answer the question to score points.Answers to questions will be in encrypted form and the teams have to decode it to get the required IOT term.<br/>\r3 Rounds:<br/>\r1st Round: A set of questions will be provided to the teams. The top 6 teams will qualify for the next round.<br/>\r2nd Round: Buzzer Round. The team which answers the question first correctly gets the point.<br/>\r3rd Round: Final face-off between top two teams.<br/>', 'PG Block CS 5005', '23 september', 'Event'),
(19, 'Congrats! You''re Placed', '100', '1000', '800', 'Tanya Gopal', '8095735719', 'The event depicts a mock placement process which consists of three rounds. The first round constitutes a general aptitude test: Basic yet Tricky. The second round is a Group Discussion on IOT in today''s world , Current affairs and Challenges faced in the Industry. The final round is an interview / stress test conducted by an industrial person or a faculty member. The best candidate wins!', 'PG CH 3002', '23 september', 'Event'),
(11, 'Courtroom Genethics', '100/Team', '1400', '750', 'Hamsanandini', '8861634539', 'Think animal testing is absolutely brutal? Or are you more inclined to believe that it''s worth it if it saves human lives? Battle with your opinions on relevant cases in this classroom courtroom debate. <br><br>- Individual event. <br>- Participants will be paired up. Each pair will be given an existing or fictional court case regarding bioethics- where one person will be the plaintiff and the other will be the defendant. They must then advocate for the cause of the entity they''re representing.<br>- No Knowledge Of Biology Or Law Is Required. The participants will be judged on their reasoning skills and delivery.<br>- The case will be given on the day of the event, and the participants will be given time to prepare.<br>-Further rules will be explained on the spot.\rTopics for debates will include IoT.eg danger of smarter systems, RFID etc.', 'M V Hall', '24 September', 'Event'),
(77, 'Criminal Case 3.0 : CYBER', '400/team of 4', '2000', '1000', 'Madhusudana HJ', '9741335084', 'Think your team can solve the crime better than Sherlock and Watson? Beat your competitors to solve a mystery filled criminal case!<br/>\r\r\rRound 1: Make use of all the random pieces of information you''ve gathered over the years about computers and IOT to solve a crossword in a given time frame to move to the next round.<br/>\rRound 2: Analyse the crime scenes and come up with a list of what could be clues to find the root cause of the series of disasters.<br/>\rRound 3: Solve the crime. Yes, it''s that simple.<br/>\r\r1)4 participants in a team.<br/>\r2)15 teams will move on to round two. In case of ties, a tie breaker round will be conducted for which the rules will be given on spot.<br/>\r3)6 teams will move on to the final round.<br/>\r4)The participants shall not procure help from anyone not in their team and no usage of cell phones.', 'Medical Electronics Department 5th floor PG Block', '24 September', 'Event'),
(28, 'Current Trends & Opportunities in IoT (BMS)', '100', 'Nil', 'Nil', 'Nidhi', '9845505253', 'Round 1: Tech Taboo - Participants will be put into groups of four and each participant will have to get their team members to guess the word written on their card sheet without using the four other clue words specified on their card. Each Participant will get one minute to get maximum word guesses. 3 Teams with maximum word guesses will qualify to the second round.<br>\rRound 2: Jargon Jam - Now each participant will compete with the other three members in the team in an intensive round of JAM (Just A Minute). Each group of four contestants will be given a minute to talk on any debatable topic regarding current trends in technology, and each contestant must &quot;JAM &quot; or buzz the current speaker in case of a)Repeating ideas, b)Stating contradictory opinions as his/her own, c) Speech errors such as stammering etc. A successful JAM or buzz will result in the caller of the JAM now becoming the speaker. Points will be awarded based on the time each contestant spoke for, and the number of accurate JAMS. 4 top scoring participants will move on to the final round.<br>\rRound 3: System Crash: All the participants will be given a common problem scenario and a unique collection of devices that he/she has at his/her disposal. They must come up with a solution using Internet of Things using the devices given to them, and pitch their ideas to the judges, explaining why their idea would be the best idea to prevent a ?System Crash?",PG Block 5003,42636,Event\r\nIoT and its Applications using Arduino,250,Nil,Nil,Sumedha,9663523435,Contents of Workshop :<br>\rIntroduction to Internet of Things (IoT)<br>\rApplications<br>\rIoT device Prototype developing using<br>\ra.Sensor<br>\rb.Actuators<br>        \rArduino Architecture<br>\rPrototype making using Arduino<br>\ra.Home automation using Bluetooth<br>\rb.Fire alarm alert<br>\rc.Smart irrigation system<br>\rd.Smart lighting<br>\re.Reverse parking system<br>\rf.Weather monitoring<br>\rg.Identification system using RFID<br>\rh.Infrared Red technique<br>', 'CS Lab', '23 september', 'Workshop'),
(40, 'Electro Blitz(BMSCE Exclusive)', '150/team of 3', '3000', '1500', 'Nikitha N', '9008858220', 'Teams will be subjected to rounds which will test their theoretical, practical and logical understanding of electronics at different difficulty levels.<br/>\r? Teams of 3<br/>\r? Teams only from BMSCE are allowed to participate.<br/>\r? Participants with valid ID cards of their respective institutions are eligible<br/>\r? Prerequisites include knowledge of basic electronics<br/>\rRound 1: WORDSWORTH<br/>\rA set of letters will be displayed on the screen using which the teams will have to frame as many words as possible in a time limit of 15 mins. The words should be related to the theme IoT.<br/>\rRound 2: KNOW THE UNKNOWN<br/>\rTeams will be given set of codes. They will have to decode each code to get a name of a component (like Bluetooth). Once they get all the components names they will be provided with one more code. On decoding that they will get the name of an IoT system. They should draw a block diagram using the components that they have, to form the given system. Clues are given at the cost of points obtained in previous round. Top 4 teams which finish the task will be qualified for the next round.<br/>\rRound 3: TAG YOUR PARTNER<br/>\rEach team will be assigned a circuit. One from each team will design it and tag his/her mate who then rigs it up. The last teammate will have to power on the circuit and get correct outputs.Absolutely no form of communication is allowed among the teammates.', 'EC 203', '23 september', 'Event'),
(43, 'Escape If You Can', '150/team of 3', '3000', '1500', 'Anjana Niranjan', '9035070780', 'Teams have to perform various tasks like algorithm design, coming up with block\rdiagrams for smart things and solving puzzles while manage their teamwork and\rtime. Teams must consist of 3 students. All students with a valid identity card of their\rrespective educational institutes are eligible to participate. Teams from different\rcolleges can form a team. In case of disputes, judges decision will be final.<br/>\rRound 1: The Road Not Taken<br/>\r1. Find a path from the start to finish line.<br/>\r2. The path will have components pertaining to IoT devices and also symbols of\rtrending IoT terminologies.<br/>\r3. Use the shortest path or collect more components along the path, scores will vary.<br/>\rRound 2: Do you have it all?<br/>\r1. Based on the game of sets<br/>\r2. The objective is to complete the flow diagram of a given IoT application.<br/>\r3. Each team has 5 passes.<br/>\r4. You can use extra passes at 50 points each, if you get another team to trade cards with you (there will be a risk of the team not having the card you want) or use your own blocks.<br/>\r5. Finally, get the whole block diagram.<br/>\rRound 3: Prison Break<br/>\rEach person in the team will have a specific task in this room. One person will be blindfolded and will be guided by the second teammate to reach the place where the clues are placed. The third person in the team is the solver, who has to solve the clues.\rRoles can?t be switched during the course of the game. Maximum time limit is 20 minutes. The first team to efficiently solve all the clues will get the key.\rClues will be based on IoT and Basic Electronics.', 'EC 2nd Floor', '23 september', 'Event'),
(52, 'Ez-Rider (geared )', '50/person', '1500', '1000', 'Nikhil J', '7406495475', 'Participation is allowed only upon the production of a driver''s license (photocopies or soft copies are accepted). Participants are not allowed to take part in the event with their own vehicle. Both for girls and boys. Participants must navigate through an obstacle course on a geared vehicle. They should not keep their feet on the ground. Time penalty of +3 seconds each time they place their feet on the ground. Time penalty of +5 seconds for collision with obstacles. Whoever finishes the course in the shortest time wins. Sensor will be fitted to the vehicle to measure the time.', 'Gopi Wall', '23 september', 'Event'),
(53, 'Ez-Rider (non-geared )', '50/person', '1500', '1000', 'Pratik R', '7829000373', ' Only for girls(boys who do not know geared). Participants must navigate through an obstacle course on a MOPED(gearlesss vehicle). They should not keep their feet on the ground. Time penalty of +3 seconds each time they place their feet on the ground. Time penalty of +5 seconds for collision with obstacles. Whoever finishes the course in the shortest time wins. Sensor will be fitted to the vehicle to measure the time.\r', ' Gopi wall', '23 september', 'Event'),
(44, 'Fury Road v2.0', '150/team of 4', '4000', '2000', 'Heethesh', '9611122852', 'A team may consist of a maximum of 4 Members. Cross-college teams are allowed.<br>\r\nAbout the Event: \r\n The aim of this event is to design and build a single remote controlled car that can compete in various challenges such as a Maze, a Football Match and an Obstacle Course. Teams must build their OWN RC Car for this event.<br>\r\nA workshop on building RC Cars will be conducted for all registered participants during the second week of September at BMSCE. The details of the workshop will be communicated to all the registered participants soon. Laptop, Soldering Iron, Batteries must be brought by the participants.<br>\r\nGeneral Rules:\r\nThe maximum dimensions of the RC Car should be within 13cm (width) x 20cm (length). Robot must be controlled manually via wireless communication (Eg: Bluetooth, Radio). The event consists of three rounds:<br>\r\n  Round 1: Temple Run: Teams are required the complete a given maze and collect a maximum number of coins within a given time period. The maze will be a flat arena with bricks placed as walls. Top scoring teams will be qualified for the next round.<br>\r\nRound 2: Football Knockouts: Teams will have to score goals in a match of football, using the same RC Car. The game will consist of two halves each of 5 minutes duration. The winners of each match will be qualified for the next round.<br>\r\nRound 3: Death Race: This final round will consist of an obstacle course where all finalists will race simultaneously to cross the finish line. Winners of this round will be declared as the winners of this event.<br>\r\n\r\n', 'PG Block, 1st floor', '24 September', 'Event'),
(3, 'Future Cities', '50/person', '4000', 'Nil', 'Hamsa', '8861115159', 'A Group event with maximum of 4 participants in a group, allowed to design their dream city. Materials will be provided.', 'Architecture Studio', '23 september', 'Event'),
(83, 'General Quiz', '100/team of 4', '6000', '3000', 'Anand K', '9449340844', 'A Regular quiz based on anything and everything. As IoT is inextricable linked to every-thing, there is a need to know about the things which involve IoT in general. This general perspective for novices in IoT is served in this quizzing format.', 'Indoor Stadium', '24 September', 'Event'),
(81, 'Gridlock 2.0', '100/team of 2', '1500', '1000', 'Sharada ', '8762666076', 'Single Round event. You will be given a paragraph containing clues.The paragraph will be loosely based on IOT. With the help of clues , you have to arrange data in a grid.The answer to the proceeding question will help you unravel the next. ', 'PG Block CS 5005 ', '23 september', 'Event'),
(85, 'H.A.M (BMSCE Exclusive)', '250/team of 2-3', 'Nil', 'Nil', 'Suman', '9980551187', 'What is the first thing that we do with internet.? communicate. HAM radio is all about the same thing in a more basic way, hence to overcome all its limitations IOT is the way out. the participants are given an opportunity to learn how to design their own FM receiver in a group of 2-3 which are formed on spot with the basic components provided being R, L, C Components, speaker and an Arduino Kit.', 'AC Lab', '24 September', 'Workshop'),
(60, 'Hands-on Workshop on IoT Applications', '500/Team of 5', 'Nil', 'Nil', 'Amarnath KV', '9980770631', 'Come and learn IoT applications with Arduino, Raspberry Pi and cutting edge App Integrated Beacon Technology with our hands on workshop on Internet of Things with Ellipsonic. All components and equipment will be provided on a use and return basis.The participants are expected in teams of 5.', '23rd of Sept (PG Block IS 4001) and 24th of Sept (ISE Lab EC Block)', '23rd of Sept  and 24th of Sept ', 'Workshop'),
(62, 'High Growth Job Roles For Engineers', '100/person', 'Nil', 'Nil', 'Aishwarya G', '7259389543', 'Industry awareness workshop on data analytics, consulting, market research, digital\rmarketing and IoT.', 'PG Block 3rd floor MBA classroom 2', '24 September', 'Workshop'),
(22, 'Hunting With Coordinates', '150/Team of 3', '2000', '1500', 'Sucharitha R', '8884801014', 'Latitudes and longitudes shall be provided and participants will use gps on their phones, reach that place and search for their next clue. Teams of 3.', 'CR 7003', '24 September', 'Event'),
(67, 'Ideas Galore', '100/team of 2', '1500', '1000', 'Abishekappa B R', '8722661138', ' Poster presentation themed ?SMART CITIES? expects participants to present the ideas to provide innovative, implementable and cost effective solutions for transportation, infrastructure, and water management system in Indian cities.2 in a team.<br/>\r              Phase I:<br/>\rSubmission of presentation should be done using ACM template.<br/>\rPoster size is A3<br/>\rParticipates should send their posters before 19 th September 2016 to ideasgalore2016@gmail.com<br/>\r All the submitted ideas will be evaluated by judges and top 10 teams will be shortlisted for Round 2.<br/>\r\r             Phase II:  Presenting the poster in front of the judge and top 2 teams will be awarded.\r\r', 'Computer Applications classroom 4', '23 september', 'Event'),
(63, 'inQUIZitive', '100/team of 2', '3000', '2000', 'Sannidhi', '7406678375', 'This is a business quiz event which will test the participant?s knowledge about\rvarious aspects of business and  related issues including IoT based business.', ' PG block  3rd floor MBA classroom 1', '24 September', 'Event'),
(36, 'Internet of Things With Intel Edison (In collaboration with EIE) {BMSCE Exclusive}', '100', 'Nil', 'Nil', 'Deeksha', '8553928159', 'Hands on Workshop followed by encouragement of students to pitch their project ideas and submit via registration form to student yatra team of Intel.<br>\rWorkshop Followed By Competition. Intel have come up with new microcontroller based boards called ?Edison? which designed for expert makers, entrepreneurs, and some industrial IOT applications. This workshop will be hands on with resource persons from Intel conducting the workshop.<br>\rRegister <a href="http://bit.ly/StudentYatra-BLR-BMS">HERE</a>', 'IT department computer lab', '24 September', 'Workshop'),
(56, 'IO SQL Workshop', '100/person', '2000', 'Nil', 'Jigar', '9408849704', 'An easy way to learn your way around IoT clouds. Attend our Workshop on basics of IOT, SQL, Knowledge about IoT cloud DBMS and queries.  A quiz will be conducted on the contents of the workshop and the winner is given Rs. 2000.', 'PG IS 4004', '23 september', 'Workshop'),
(34, 'IoT & its Applications using Arduino', '250', 'Nil', 'Nil', 'Sumedha', '\r\n9663523435', 'Contents of Workshop :<br>\r\nIntroduction to Internet of Things (IoT)<br>\r\nApplications<br>\r\nIoT device Prototype developing using<br>\r\na.Sensor<br>\r\nb.Actuators<br>	\r\nArduino Architecture<br>\r\nPrototype making using Arduino<br>\r\na.Home automation using Bluetooth<br>\r\nb.Fire alarm alert<br>\r\nc.Smart irrigation system<br>\r\nd.Smart lighting<br>\r\ne.Reverse parking system<br>\r\nf.Weather monitoring<br>\r\ng.Identification system using RFID<br>\r\nh.Infrared Red technique<br>\r\n', 'CS Lab', '23 September', 'Workshop'),
(27, 'IOT Code-A-Thon', '100', '1500', '1000', 'Karthik R', '9741036752', 'Two rounds, each of 2 hours duration.<br>\rParticipants will be given a problem set in the first round and will be asked to code their solutions on the computer provided.<br>\rBased on their performance, they will be selected for the second round.<br>\rIn the second round, they will be given a harder problem set.<br>\rThe participants with the best scores at the end of both rounds will win cash prizes\r&; T-shirts by HackerEarth.<br>\rParticipants will be allowed to code in C, C++ or Java.<br>', 'Internet Lab', '23 september', 'Event'),
(30, 'IOT Ideathon {BMSCE Exclusive}', '200/Team of 3 or 4', '10000', '3000', 'Govind', '8971526662', 'Part I : Startup Sutra by Kedar Kulkarni\rKedar, CEO and founder of HyperVerge, will deliver an interactive talk on how HyperVerge started off in IIT Madras and went on to raise funding from the biggest VC firms in the Bay Area. The talk will cover different stages in the lifecycle of a startup, what one needs to do at each stage and what it takes to be an entrepreneur. He will also delve into the space of computer vision and how it can contribute in the IoT age.\r<br><br>Part II : Magic Share - PhaseShift Ideathon\rJust like hackathons where groups of students work on hacking a project together in a short period of time, the Ideathon will be an open contest where the best minds of any background from different colleges (in groups of 3-4 per team) will work on generating innovative ideas on a real life problem statement (in the IoT space) in a short period of time. At the beginning of the competition, the problem statement will be released and teams will have one hour to play with the prototype/app/case, understand its working, suggest changes and generate new, creative ideas revolving around the problem statement. The merit of each submission will be judged based on the creativity of the ideas, feasibility and relevance.', 'PG Block CS 5002', '23 and 24 September', 'Seminar and Competition'),
(38, 'IoT In Application Of Renewables Workshop', '100', 'Nil', 'Nil', 'Kavya R', '9686302812', 'The participants will be exposed to smart energy systems like smart meters etc.The workshop is organized by a pioneer in the field,Fluxgen Technologies,a start-up ranked among top 50 start-ups of the country.The real life applications of these concepts is infinite,and incorporation of IoT,learnt during the course of the workshop can be applied to other fields also.In addition participants will also be awarded certificates by the organizers.<br>', 'Library Auditorium', '24 September', 'Workshop'),
(57, 'IOT Intelligence', '120/Team of 2', '3000', '1000', 'T Mithun', '9535262771', 'A gruelling team coding event where participants are given real life IoT problems and a coding solution is expected from them. Participants are expected to enter in teams of 2.<br/>\rPreliminary round ? Walk-in any time from 9am - 2pm to an open round where an IoT problem is given to the participants and they are expected to give a solution, but they are timed. The fastest 15 teams progress to round 2.<br/>\rSecond Round ? A common problem is given to the 15 teams. Fastest 7 will be selected for final round.<br/>\rFinal round ? A common problem is given to the remaining teams. The quickest team to solve will be declared the winner.', 'ISE Lab ECE Block', '23 september', 'Event'),
(29, 'IoT Tech Hunt', '150(Individual), 250(Team of 2 and 3)', '1500', '1000', 'Siddhartha', '9454178342', 'Before the start of the event a brief tutorial on how to code on an Arduino board will be given to the participants.<br>\r\nDetails:<br>\r\nAn encrypted key that reveals a location in the CS/TC block is given to each group.<br>\r\nOn successfully decrypting the key, a location will be obtained. At this location a sequence or a task that must be completed on an Arduino Board will be given.<br>\r\nOnce the task is completed successfully, the next encrypted location will be\r\n                         given to the group.<br>\r\nThe group to cover maximum locations/finish the entire course at the end of 2\r\nhours will win the event.<br>\r\n', 'CSE Seminar Hall(1st floor EC Block)', '24 September', 'Event'),
(89, 'IoT Techniques and Implementation Using Arduino', '750/team of 3', '2000', '1000', 'Sarika J', '9611591382', '?IoT applications using sensors.<br/>\r?Using IoT technologies to improve industrial requirement ,with specialized focus on the areas of industries, media, IT, and networks.<br/>\r?To learn how IOT it is useful in social cause like using connectivity to address poverty, human rights and climate change.<br/>', 'PG Block 2nd floor EEE DSP Lab', '23 and 24 September', 'Seminar'),
(6, 'JIG Saw', '100/Group of 4', '1500', '1000', 'Chaitra U', '9482860233', 'Team event which involves two parts. First, the participants have to paint based on a given theme. Later, there will be an element of surprise. Materials to be brought by the participants. No. of participants ? 4 per group', 'Architecture Studio', '23 september', 'Event'),
(73, 'Junkyard Javelin', '300/team of 2', '1500', '1000', 'Ajay Samuel Mathew', '9480413996', 'This Event Requires the Participants to construct a Throwing Mechanism from the given Junk to throw a ball, the range being the deciding factor to get a winner.We are integrating IOT and Junkyard Javelin by making use of iot based measuring system (Sonar being used in this case). This will measure the distance traversed by the ball, process it and calculate the initial velocity of the ball by taking in the Release angle as input. All teams will get 3 chances with the farthest out of the three considered for getting a winner.In case of a tie, the one with the highest sum of the 3 chances combined wins. No Slingshots allowed.', 'EC block Parking lot', '24 September', 'Event'),
(49, 'LaTeX Workshop', '200/person', 'Nil', 'Nil', 'Srinivas S ', '8884171828', 'LaTex is a free program for mankind scientific and technical documents and is the standard for professional in many STEM fields. Its purpose is to make it easy to write elegant technical documents. All participants will bring their personal laptop. Software will be provided.', 'BSN Hall', '24 September', 'Workshop'),
(24, 'Life saving applications of laser scanning(W) ', '250', 'Nil', 'Nil', 'Manoj V', '9538575812', 'One day workshop on &quot;Life saving applications of laser scanning &quot; in civil engineering perspective will be taught by Ansari Precision Instruments Pvt. Ltd. In case of floods, landslides,during defence?etc. laser scanning technology plays a very important role in identifying people,strategic points in surveying or any particular object. The data monitoring of which will require Internet. Students are required to bring their laptops.', 'M V Hall', '23 september', 'Workshop'),
(58, 'Logo Mania 3.0', '50/person', '3000', '1000', 'Rayapeddi', '8095372333', 'The most awaited event with highest participation is here, put your logo quiz (the game you play in class) skills to test, at Phase Shift; with a IoT based logo mania.<br/>\rPreliminary memory round ? A written quiz is given. It will have 30 logo based questions. Top 40 participants will be selected for the second round. <br/>\rSecond round ? A slide containing 80 logos will be shown to the participants for 30-40 seconds. Soon after, the participants should write down as many logos they can remember.  Top 15 will be selected for final round. <br/>\rFinal round ? A logo based quiz, which is conducted by a quiz master. The participants are expected to answer. The best participant will be declared winner.', 'PG Block IS 4001', '23 september', 'Event'),
(39, 'Machine Learning {BMSCE Exclusive}', '100', 'Nil', 'Nil', 'Sachin K', '9060630130', 'In today''s world of IoT and ''Smart systems'', it is becoming increasingly popular to add on to the user experience with technology, an element of machine learning, which comprises of techniques like pattern recognition, artificial intelligence to name a few.\rThis workshop will provide the students an introduction to the world of machine learning, and consequently teach them about the concept of probability theorems, neural networks and data structures, and their applications to develop algorithms for real-life data using suitable programming languages like Python, Java and Julia.', 'BSN Hall', '23 september', 'Workshop'),
(54, 'Materialistic', '100/Team of 2-3', '1500', '1000', 'Apoorva', '9740041642', 'Team of 2/3. Round 1: Jenga , game based on structures. Round 2:Connect , Derive answer from three related pictures. Round 3: Junkart , build useful items with provided junk. Jenga sets as well as junk will be provided. Internet usage permitted only for answering. Participants need to have a mobile phone with working data connection.', 'IEM CR 101 ( Mech block 1st floor)', '24 September', 'Event'),
(45, 'Mega Mind', '150/- per team of 3', '3000', '1500', 'Srinivas S ', '8884171828', 'The event comprises of three rounds in which, the first round shall be a written round and the other two shall be hardware-based rounds. The fastest of them all who can maintain accuracy takes home the prize!!.\r? A team must consist of three participants. Inter-collegiate teams shall be allowed.\r   Round 1: Roll And Don?t Stroll\r? Questions of varying difficulty levels are distributed into different sets.<br/>\r? The teams roll a die and the number decides the difficulty level of their question set.<br/>\r? 40% of the questions in this round will pertain to IoT and Wireless Communication.<br/>\r? Each team will be given a maximum of 30 minutes to answer the set.\r   Round 2: Ready Set Glow<br/>\r? Each problem will involve a circuit, corresponding to a question, in which a component which uniquely completes the circuit will be missing.<br/>\r? The teams will have to connect the correct black box which will answer the question and\rcomplete the circuit.<br/>\r? 40% of the questions in this round will be related to IoT and Cloud computing.\r   Round 3: Rectifier<br/>\r? Each team will be given a pre-constructed circuit which contains unwanted and redundant\rcomponents.<br/>\r? The team will have to first identify the working of the circuit, and then optimize it by identifying and removing dispensable components without affecting the circuit?s functioning. For each component removed, they get a block of an IoT circuit. These blocks must be put together to get a complete IoT circuit.<br/>', 'EC 201, AEC Lab', '23 september', 'Event'),
(23, 'Mixed Bag', '100/Team of 2', '2000', '1500', 'Nishal S', '8792522497', '2 Rounds shall be conducted. Round 1- Case study (Topic will be given 3 days prior to the event and will be related to IoT in Civil engineering). <br> Round 2-Quiz round (Questions related to IoT in civil engineering). Participants will be required to bring their laptops. <br> Teams of 2. ', 'PG 7010', '23 september', 'Event'),
(12, 'Molecular Simulations using GROMACS (W)', '100', 'Nil', 'Nil', 'Avinash K', '9741500191', '-Gromacs is a molecular dynamics package primarily designed for simulations of proteins, lipids and nucleic acids. <br> - Workshop involves hands on session on molecular assemblies of liposomes. <br> -Workshop will follow after a free seminar on the tool. Concepts of IOT may be included in the seminar by the resource person.', 'Bio-Informatics Lab', '24 September', 'Workshop'),
(78, 'Mystery Inc', '200/team of 2', '2000', '1000', 'Vinutha', '9741058711', '2 participants per team.The event requires basic understanding of electrical, electronics and IoT concepts to solve the given problems.Usage of any electronic devices or taking outside help is NOT allowed.<br/>\r\r\rRound 1- A written round where the participants will have to answer puzzles and solve riddles fast enough to move onto the next round.<br/>\rRound 2- A round where top 10 teams from the previous round will be selected to solve the clues leading them to the next successive location. In the end, they will have to answer the given questions correctly to be given the components for the next round.<br/>\rRound 3- 5 top teams from the previous round will be selected to complete the IoT based circuit and implement it.<br/>', 'Medical Electronics Department 5th floor PG Block', '23 september', 'Event'),
(46, 'Online Questionnaire(IEEE)', '50/person', '1000', '500', 'Rishab', '7760534154', 'This is an individual event that consists of complex questions under the following 5\rdomains:-<br/>\r2) Digital Signal Processing & Microcontrollers<br/>\r4) RF / Microwaves / Antennas / Waveguides<br/>\r5) Analog, Digital and Computer Communication<br/>\r6) Analog  and Digital electronics / Digital IC?s<br/>\rThe questions could be MCQs or subjective.\rThe event will be hosted online on a portal which will be made available to the\rparticipants by mail. The portal will be opened at 7pm on 23/09/2016 and will be\rclosed at 11pm.<br/>\rAll participants who have registered online for the event must mail a scanned copy of\rtheir ID card to the event co-ordinator (rishab9996@gmail.com)<br/>\rDuration:- 4 hours', 'Online', '23 September (7PM to 11PM)', 'Event'),
(2, 'Panel Discussion (BMS)', 'NONE', 'Nil', 'Nil', 'Rachana H', '9740146274', '4-5 architects discuss based on a given topic. <br> Topic: Contemporary Architecture / Sustainable Architecture', 'Library Auditorium', '23 september', 'Seminar and Competition'),
(55, 'PANIC!', '150/Team of 3 or 4', '2000', '1000', 'Pranab D', '9902103103', 'Round 1 : Geoguessr www.geoguessr.com<br/>\rUses google streetview to drop you off at a random location on earth. You need to navigate to find clues about your location. Then after gathering intel, make an educated guess on the map. The closer you are to your actual location, The more points you get. Max 5000 per round. 5 rounds.Team of 3 or 4. (Left to their choice).2 people per team allowed inside lab.Each team given link for the same 5 locations. Points are added to or subtracted from the total score if they finish the challenge within the given time, or use the internet to google.<br/>\rWithin 15 minutes : +5000 points<br/>\rWithin 20 minutes : +4000 points<br/>\rWithin 25 minutes : +3000 points<br/>\rGoogle once  : -1000 points<br/>\rGoogle twice : -5000 points<br/>\rEach team is allowed to Google only once per round, with a maximum of 2 lifelines allowed per team.Time limit for the first round is 30 minutes.<br/>\rRound 2 : Escape Room <br/>\rThe top 5 teams from the previous round will be selected. Each team will be locked into the room. Solving each clue will lead to the next. Upon solving the final clue, a password is revealed. They must use this password to escape from the room. The theme is " Bank Heist". Each team will start from within the bank and try to break into the safe. A rare artifact in the safe is what the teams are after. Time will be added for utilizing lifelines. The two quickest teams to escape the room wins.<br/>', 'ERP Lab, Taylor Hall', '23 and 24 September', 'Event'),
(50, 'Paper Presentation', 'IEEE SSIT Members - Free\n<br>IEEE members - 300 INR\n<br>Non-IEEE members - 400 INR\n<br>Teams of 1-4', '3500', '2500', 'Tarun Varma', '7406323829', 'It should be 2-6 pages long PDF manuscript in IEEE conference format. All the papers will be peer reviewed. The paper should have an original idea, implementation, simulation and experimentation. The IEEE plagiarism policy is applicable to all submissions. <br/>\nSelected papers will be published in journals.<br/>\nLast date of Submission: 16th Sep 2016<br/>\nThe presentation of accepted papers will be on day of Phase Shift.<br/>\nEach author of the accepted paper will get a participation certificate.\n\nSponsored by IEEE SSIT ES Joint Chapter', 'BSN Hall', '24 September', 'Event'),
(86, 'Pictonnect', '100/team of 2', '1000', '500', 'Sarayu M', '9880106670', 'In collaboration with Mechanical department. How well are you being updated to the current trends and applications of IOT technology advancements.? Come test and update yourselves. Pictonnect will consist all of it with a twist. Team of two will participate in two rounds. In the first round guess the word Related to IOT  with the pictures shown. First ten teams will be selected to the second round , in which the output and input to a system is to be given  through the keywords guessed found in round one.', 'EC 207', '24 September', 'Event'),
(5, 'Picture This!', '100', '1000', '700', 'Chamundeshwari', '9886181603', 'Day 1: A brief introduction about the theme given to the participants on the day of the event. <br>Day 2: The participants are desired to submit their works by 12 PM and they are evaluated on the same day. <br> Participants must get any devices that can be used to capture images with a minimum of 8 megapixels. ', 'Architecture Studio', '23 september', 'Event'),
(4, 'Product Design', '100/Group of 2', '1000', '700', 'Yashas N R', '9008576055', '2 Participants per group will have to design a composition on a tile or design a Furniture. Materials will be provided.', 'Architecture Studio', '24 September', 'Event'),
(90, 'Project Display On Home Automation', '200/team', '3000', '2000', 'Chetna B', '9880928324', 'Participants will demonstrate and showcase their project.Evaluation of the project will be done by the industrial representative.Use the knowledge of sensors and various communication protocols. Use the concept for their mini / major projects multi_disciplinary areas.Application of IOT', ' IT Classroom 2, PG Block', '23 and 24 September', 'Event'),
(70, 'Project Emblazon', '100/person', '1500', '1000', 'Anil Karwa', '9739280907', 'Demonstration of  IoT project developed by the participant. Participants must get their project material for demonstration. Project should be demonstrated in front of the judge.', 'ICL Lab, PG block 1st floor', '24 September', 'Event'),
(87, 'Project J', '300/team of 3', '1000', '750', 'Rohini Raj', '8553578476', 'Team of 3. Teams will be given electronic junk. They have to come out with a working IOT related device using the Junk. Details of the junk provided will be intimidated 1 week prior to event to all registrants. ', 'AC Lab', '23 september', 'Event'),
(84, 'Project Race (BMSCE Exclusive)', '250/team of 4-5', 'Free kits', 'Free kits', 'Sushmitha Krishna', '7406997920', 'The Internet of things can change the way citizens live, travel, and take care of each other. Arduino has been part of the conversation since early on. Teams of 4-5 members will perform in two rounds, first round is a common project to the all the teams followed by second round in which only 3 teams will be selected will be comprise of a little more advanced projects .In both rounds Arduino kits ,user manual and all necessary components are provided to all the teams . First two winners will get to take away their kits with them.', 'MC Lab', '24 September', 'Event'),
(25, 'Retrofitting & Maintainance of Structures Using Smart IOT Devices', '150', 'Nil', 'Nil', 'Nyamagouda', '7411858821', 'In collaboration with Information Science Department.A workshop on maintenance of Buildings using smart devices. Gives an idea of maintainance of buildings using smart devices.', 'PG 6002', '24 September', 'Workshop'),
(13, 'Rise of Mutants', '150/Team', '1500', '750', 'Nihal K', '7760284612', 'There will be two rounds. All scenarios must be explained scientifically. Each team will have 2-3 minutes to present their findings. Scoring will be done based on scientific accuracy and presentation skills. Participants need to get their own devices (smartphone, laptop) with internet access.', 'BT Classroom', '24 September', 'Event'),
(59, 'Route IT', '100/Team of 2', '3000', '1000', 'Nataraj', '9739646185', 'Is an exciting team treasure hunt event modelled after recent sensation Pok?mon Go.Participants are expected in teams of 2 students each.<br/>\rPreliminary round ? A basic IoT quiz is conducted. Top 20 teams progress to round two.<br/>\rSecond round - 50 QR code Posters are scattered around the campus of BMSCE, the top 10 teams to find as many of these codes and retrieve passwords after scanning them, proceed to final round.<br/>\rFinal Round - 5 private network routers to be placed in various spots around campus.<br/>\rThe teams are then set off on a password hunt, 5 at a time.The teams are given a beginning router name, which they will have find and solve a small puzzle to find the password and next router name.The Fastest team to retrieve 3 consecutive passwords wins.', 'PG IS 4004', '24 September', 'Event'),
(16, 'Scifi Battle', '100/Team of 2', '1400', '900', 'Priyanka S', '7795240104', 'Teams?of?2?have?to participate. <br> There?will?be?a?preliminary?round with elimination before the final round. <br> Questions?pertaining to IoT will be included. <br> Questions?can?be posed in the form?of logo identification and/or pictionary?as?well.<br> Googling?will?lead?to disqualification.', '3001 PG Block', '24 September', 'Event');
INSERT INTO `events` (`ID`, `EventName`, `RegFee`, `First`, `Second`, `Coordinator`, `Contact`, `Description`, `Venue`, `Date`, `Type`) VALUES
(47, 'Short Movie Making', '150/team of 4-6', '3000', '1500', 'Faraz Khan', '8050332624', 'Teams have to showcase their creativity in short video to capture the importance of technology.\rA team may consist of a maximum of 4-6 participants. Students from different educational institutes can form a team. \rAll students with a valid identity card of their respective educational institutes are\religible to participate. Teams are allowed to use any media for recording and editing. Teams will have\rto bring their own equipment. In case of disputes, judge?s decision will be final. Video Recording\rDevice, Laptop with editing software must be brought by participants.<br/>\rGeneral Instructions:<br/>\rThe reference video will be sent to their respective mails and will be informed on phone. The video\rcan?t be a montage, slide show movie.\rJudges decision will be final.<br/>\rGameplay:-<br/>\rRound 1: Remakedaaa!<br/>\rIn this round, all participating team will be given a reference video, which they need to remake. The\rreference video will be released to all participants 5-6 days before the event. The finished. Remake\rshould be based on the theme IoT. All videos will be screened on day 1 and 6 teams will be selected\rfor 2nd round.<br/>\rRound 2: Off the Spectrum<br/>\rAfter round 1, selected teams will have to shoot another video inside the campus itself. Genre of their\rchoice can be selected and the video needs to be prepared on the theme IoT. They can edit the video\rovernight and submit it for screening on next day.\rThe length of the video should be 5 mins max.', 'EC 201', '23 and 24 September', 'Event'),
(14, 'Start-Up Wars', '150/Team', '1500', '1000', 'Jonathan J', '9632221994', ' Ideating start up enterprises in the biotech field (pharma, agri, env, etc). <br>  Max of 3 participants per team. <br> All teams are to report at the allotted time where further details will be given. <br> All teams will participate in all the rounds. <br> Winners will be judged by points earned. <br> Teams that have integrated IoT into their start up ideas will earn bonus points.\r', 'BT Classroom', '23 september', 'Event'),
(8, 'TARDIS', '50', '1000', '500', 'Ankith R', '9731160844', 'Are you a capable of becoming a Time Lord and forgo all barriers and travel through space? Step into the TARDIS and experience the universe. The event will entail knowledge sharing of how IoT is used in space exploration and astronomy. <br> Rules:This quiz consists of three rounds . Total duration of the event is 90mins inclusive of all the three rounds.Cross College teams are allowed.No Use of Electronic Gadgets which otherwise will lead to disqualification. Teams of 2. <br> Round 1- Initiation game: Race time to solve puzzles related to the cosmos.(PS- A little grasp of TV series isn''t so bad after all.) <br> Round 2-Guardians of the Galaxy : To be a guardian, you need to know the Galaxy like the back of your hand.(PS-Who knew recognising faces and patterns would come so handy? ) <br> Round 3-Oblivion : Are you oblivious to everything happening around your world or are you really listening? Find out who is communicating to you by cracking the riddles.', 'PG 6004', '23 september', 'Event'),
(32, 'Tech JAMboree', '100', '1000', '750', 'Apoorva Shetty', '7760600390', 'This workshop covers<br>\r1. Drawbacks(Security issues) in IoT<br>\r2. Current technological trends in IoT<br>\r3. Scope for growth(Research opportunities) in IoT<br>\rDetails:Cloud computing has become an integral part of IoT and performance of sensors largely depending on the performance of cloud. However,due to various challenges in cloud computing such as high latency, intermittent communications,bandwidth and energy constraints, etc., a new paradigm called fog computing is shaping up lately.Moreover, Many of such applications such as remote sensing, AR, VR based communication,etc., require very low latency communication with higher degree of reliability and availability.For such highly demanding applications Tactile Internet has been envisioned. In addition, all these advanced technologies require very sophisticated security and privacy mechanisms in place.Thus in this workshop we plan to start with Fog Computing and Communication ?which is more relevant for IoT or Sensor Networks and then proceed towards<br>\rTactile Internet ? as the way forward for our future, and the end plan to take up the security/privacy challenges related to IoT frameworks.', 'PG block CS 5004', '23 september', 'Workshop'),
(33, 'Techzibition', '200', '', '', 'Sumedha', '9663523435', 'Provides a platform for budding innovators and creators to present their ideas \r\nand projects related to IoT.\r\nThe event is categorized into 2:<br>\r\n1. Idea based<br>\r\n2. Prototype based.<br>\r\n<br>\r\nParticipants can participate in either category and they will be evaluated separately.First & Second prizes will be given in each category.<br>\r\nParticipants should get:\r\nPresentation - if the participants are proposing an idea.<br><br>\r\nPresentation and prototype if they have the product implemented.\r\n', 'CR 101', '24 September', 'Event'),
(17, 'The Great Mole Relay Race', '100/Team of 4', '1600', '800', 'Rashmitha', '7795645763', '1st round- 4 simple equations to be balanced. <br> _2nd round- Enhanced stoichiometric questions including no. of moles, avogadro''s number etc., for the equations given in 1st round. _<br> 3rd round- Picture quiz. <br>_4th round- Crossword puzzle having clues for terminologies of IoT in Chemical Engineering industries.\r<br> Rules <br> Elimination- Teams completing the fastest in every round will be given the limited no. of batons (scrolls of questions for next round), leading to successive elimination. <br>No mobile phones, smart watches and other electronic gadgets to be used during the race. <br> Dropping of baton leads to disqualification. <br> Scientific calculators without the covers can be used (brought b y participants).', 'Outside Library Auditorium', '24 September', 'Event'),
(93, 'The Prototype', '100(Team Event 2 members in one team)', '1000', '750', 'Akash', '9663061644', 'The Molde presents The Prototype.<br>\r\n\r\nParticipants will be asked to build a paper prototype of an IOT app for which the idea will be given on-spot at the event.<br>\r\n\r\nNo prior coding skills or knowledge of any software is required. All we need you to bring are your thinking caps, lots of creativity and maybe a notebook to jot down all the things you''re going to learn!<br>\r\n\r\nJoin us to learn a little more about the most essential step that goes into making apps like Uber, Facebook, Tinder, etc and what made them the unicorns they are today by interacting with an industry expert.<br>', 'Classroom 5004, Pg Block - 5th Floor', '24 September', 'Event'),
(21, 'The Sprinting Chemist', '100/Team of 3', '1600', '800', 'Shireesh Gupta', '8088804913', 'Team will be of 3 peoples. Each team will be assigned one starting element. A set of clues corresponding to locations in the college will be given. Every location will correspond to a compound or element. <br>_Teams will have to go to the locations and write down the combinations they can make from the elements and compounds they already have. Teams will be informed in the sheet itself which clue will be leading to which element or compound so that they can preferentially solve clues depending on the elements and compounds they already have in their inventory from the starting element or from compounds collected by solving previous clues. <br>_Time limit of 1 hour is decided. Team making maximum compounds will win', 'PG CH 6002', '23 september', 'Event'),
(75, 'Utility Chain', 'Rs.100 per person, 200 for a team', '1500', '1000', 'Anand M', '7204216379', 'In 1st round, the competitors will have to make the specific model using workshop tools. To include IoT into the event, we will have one die for a model in which the model of the competitor should fit in. If the model fits in the sensor should indicate it by glowing lights.\rIn 2nd round, a presentation on problems utility chain management with iot solutions. Participants must participate in both rounds.', 'Mechanical workshop', '23 september', 'Event'),
(88, 'Workshop and competition on App Development', '500/team of 3', '3000', '2000', 'Anusha KG', '8892963124', 'Garner knowledge of how to get started with app development. Use the concept for their mini / major projects. Use in IOT. Associated with Herman Technologies.\rRequirement:__Students should possess basic programming skills.', 'IT Project lab PG BLOCK 2nd Floor', ' 23 and 24 September ', 'Workshop'),
(91, 'Workshop And Competition On Sensor To Cloud Connectivity\n (BMSCE Exclusive)', '200/team of 4-5', 'Internship', 'Nil', ' Neha M', '8197328283', 'Interface sensors to cloud by using different communication modules for IoT and INDUSTRIAL INTERNET OF THINGS (IIOT).<br/>\rDay 1:_ Theory on sensors and communication on with hands on experience to establish IOT framework , Temperature, humidity and CO2 Sensors and Emergency lighting will be used as basic hands on for sensors to communication  modules. IoT demo with Roomba vacuum cleaner _ A Multiple sensor , iot enabled moving cart to showcase a complete IoT solution in IoT<br/>\rDay 2 :_ From gateway to cloud Theory and hands on exercise. ,Web based SCADA widget?s will be built as hands on exercise one Telamon gateway from Sunlux shall be provided for the event.<br/>\rThe event shall have a competition in the second half of  DAY 2 for giving a solution with sensor to cloud connectivity based on workshop learning. Use of Object Oriented Programming / C Programming or  modelling software to interface various types of sensors.<br/>', 'RK Hall PG BLOCK 1st Floor', '23 and 24 September', 'Workshop'),
(18, 'Workshop on CFD (BMS)', '150', 'Nil', 'Nil', 'Shubham', '9482100864', 'Hands on workshop to learn ANSYS from experienced industry personnel. The event will help students understand the uses of computational fluid dynamics and its applications in Internet of things.', 'Chem Lab', '24 September', 'Workshop'),
(76, 'Workshop on Home Automation', '50/person', 'Nil', 'Nil', 'Shubham', '8088439668', 'This workshop will help participants to get to know about Iot in this field. Mr Aravindan will be briefing them about the current trends in this sector and demonstrate some of the models with his kits.', 'MESH Hall, Mechanical Department', '24 September', 'Workshop'),
(NULL, 'Workshop on Invest like Warren Buffet''', '100', 'Nil', 'Nil', 'Madhuri S', '9066642452', 'An Introduction on Warren Buffet and Pillars of Investment and how IoT can be used\r\nto make better investments decisions.\r\n', 'MBA classroom 1 (PG block 2nd floor)', '23 September', 'Workshop'),
(42, 'Workshop on IoT by MediaTek on LinkitOne Board', '200/team of 3', 'Nil', 'Nil', 'Jayprakash', '9632024724', 'The students will have a hands on experience with the working of IoT. The various aspects of IoT like hardware, cloud platform and the application device will be discussed. <br/>\rThe LinkitOne Board will be used to interface various other modules like WiFi, GPS and GSM. <br/>\rIt will also explore the different ways to send data to the cloud and show some action on the application device. <br/>\rReceiving sensor values/data from the application device and reacting to it will be another domain of interest. <br/>\rOverall workshop aims to teach the students everything that one needs to know about IoT.<br/>\rTeams of 3, first come first serve. Max teams ? 20', 'eyantra Lab, PG block 6th floor', '24 September', ''),
(68, 'Workshop on Recent advances in IoT', '50/person', 'Nil', 'Nil', 'Nagashree B A', '8904641443', 'Today IoT is the main force driving change in industries and society. IoT will be the smart technology of tomorrow and 2020 will be the year of IoT. IoT will be seen as the catalyst responsible for leveling the playing field between humans and machines. The objective of the workshop is to explore the recent advances in Internet of Things (IoT). Content: Introduction to IoT Architecture and Technologies.Exploring various use cases of IoT.Current trends in IoT.The future of IoT.', 'FDC Hall', '24 September', 'Workshop'),
(31, 'Workshop on understanding Business Architecture in IoT context(BMS Exclusive)', '100', 'Nil', 'Nil', 'Nidhi Jagadeesha', '9845505253', '<strong>Details</strong>: A Workshop on Understanding Business Architecture in IoT Context to bring Human Value.  A Case Study on Concept of Design & Architecture to meet this expectation. Get a Glimpse of What Industry perceives as VALUE from Technology. It has Work Bench to learn hands on.<br><br>\r\n<strong>Outcomes</strong>: IASA Global will identify young innovators, who can nurture with BMSCE and Industry collaborators in the next few years of their journey to become Professionals in Information Technology, Applied Engineering, Industry Business Modeling and Process with Innovation Themes (IoT, Cloud etc.) & Business Value and Capability Mapping. Its a Cross Engineering student benefit. Its meant for both UG and PG Students.<br><br>\r\nThings participants should carry: Laptops.\r\n', 'PG Block CS-5001', '23 September and 24 September', 'Workshop'),
(41, 'Workshop on Wireless Sensor Networks (WSN)', '200/team of 3', 'Nil', 'Nil', 'Bharath R', '8792458460', 'Resource  person: Intel and Nihon Communications.\rThe content of the workshop will be:<br/>\rInterfacing the sensors to a control unit<br/>\rCommunication of real time data from sensors to control unit.<br/>\rIntroduction to Bluemix Cloud Platform<br/>\rIntroduction to IoT application demo.<br/>\rTools required for WSN deployment<br/>\rCloud storage and analytics.<br/>\r        The workshop will begin with a talk by Intel on IoT and its applications.<br/>\r        The hands on workshop  will be conducted by Nihon Communications.', 'Digital Electronics Lab PG Block 1st Floor', '24 September', 'Workshop');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
